import type { Metadata } from "next";
import "./globals.css";
import { GlobalContextProvider } from "@/components/GlobalContext";
import App from "@/components/App";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
  sidebar,
}: Readonly<{
  children: React.ReactNode;
  sidebar: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className="antialiased">
        <GlobalContextProvider>
          <App sidebar={sidebar}>{children}</App>
        </GlobalContextProvider>
      </body>
    </html>
  );
};

export default RootLayout;
