import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
  sidebar,
}: Readonly<{
  children: React.ReactNode;
  sidebar: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="w-screen h-screen flex">
          <div className="bg-gray-200 w-[min(30rem,40vw)] flex-shrink-0 h-full">
            {sidebar}
          </div>
          <div className="w-full h-full">{children}</div>
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
